### ISSUE TITLE
wait-wake problem

### ISSUE THREAD

**Issue by MedovTimur** [easyshellworld/rich-gear-academy#4]
Hi!
Great work, but I have a question: what happens when the program wakes up, after you have set it to `wait` here

https://github.com/easyshellworld/rich-gear-academy/blob/8a33e5bb22249d380b4d7ad4d9d21b00609e0866/gamesession/src/lib.rs#L115-L133

I want to know what path your code will take when the `wake` is triggered

And could you create a pull request and set up CI tests so I can see that the tests pass

**Comment by easyshellworld** [comment]
thanks,i will test.
